[secrets]
OPENAI_API_KEY = "QQExs9cGYvDjBQUrOG13u2KDhK9rXGoOyDByuMUWLN_K27d61Q0AU7v6LK3c5O6L3dCXOtZUvgT3BlbkFJHGIX2k2ij1a4ePIvFp5iVj2McT_zvRNNzC1m5A7u0yR_G"
DID_API_KEY = "a3VvY2hpbGlAZ21haWwuY29t:HFD1OdkHSMVAOinjzvn9v"
