AZURE_SPEECH_KEY = "79JQ3eGV97b39wxpSy3sUnazxtddHIPXBddjSep47uLxvAeudOCUJQQJ99BLACi0881XJ3w3AAAYACOGJxct"
AZURE_SPEECH_REGION = "japaneast"
DID_API_KEY = "a3VvY2hpbGlAZ21haWwuY29t:e4xK3Qarg2-S-r8YOLArc"
