AZURE_SPEECH_KEY = "9dWTGxS65ClqXhslTDJ6OOrjzoS8jlRriyVgfnhe4IPPjErVeEHqJQQJ99BLACi0881XJ3w3AAAYACOG9VOZ"
AZURE_SPEECH_REGION = "japaneast"
DID_API_KEY = "a3VvY2hpbGlAZ21haWwuY29t:e4xK3Qarg2-S-r8YOLArc"
