AZURE_SPEECH_KEY = "2usjwgDOXe1S425IaXviKTO6tT0YdkNtoMoqOA2436nQXeogDeAaJQQJ99BLACi0881XJ3w3AAAYACOG9JwV"
AZURE_SPEECH_REGION = "japaneast"
DID_API_KEY = "a3VvY2hpbGlAZ21haWwuY29t:e4xK3Qarg2-S-r8YOLArc"
