AZURE_SPEECH_KEY = "4HgaEBvOOypumGqYzy2ofoGFQj3bZRPDU0bdX6dQvx0kCeMsXC5JJQQJ99BLACi0881XJ3w3AAAYACOG5uOO"
AZURE_SPEECH_REGION = "japaneast"
DID_API_KEY = "a3VvY2hpbGlAZ21haWwuY29t:e4xK3Qarg2-S-r8YOLArc"
